# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzotUPlUP62eBeCVFDaqGN4Jg3n-0HmL
"""

# -*- coding: utf-8 -*-
"""LogisticRegression_Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8PXdcmPsrQtqyVXpET3sgghAMr_MCg5
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline
#"%matplotlib inline" will make your plot outputs appear and be stored within the notebook.

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('insurance_data.csv')
df.head()

plt.scatter(df.age,df.bought_insurance,marker='+',color='red')

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.9,random_state=10)
X_train.shape

X_test

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

X_test

y_test

y_predicted = model.predict(X_test)
y_predicted

model.score(X_test,y_test)

model.predict_proba(X_test)

y_predicted = model.predict([[60]])
y_predicted

#model.coef_ indicates value of m in y=m*x + b equation
model.coef_

#model.intercept_ indicates value of b in y=m*x + b equation
model.intercept_

#Lets defined sigmoid function now and do the math with hand
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

def prediction_function(age):
   z = 0.127 * age - 4.973 # 0.12740563 ~ 0.0127 and -4.97335111 ~ -4.97
   y = sigmoid(z)
   return y

age = 35
prediction_function(age)

"""0.37 is less than 0.5 which means person with 35 will not buy the insurance"""

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import metrics
import matplotlib.pyplot as plt

# Upload dataset
from google.colab import files
uploaded = files.upload()

# Check uploaded files (important!)
import os
print(os.listdir())

# Load dataset (use exact filename from above output)
df = pd.read_csv('iris (1) (3).csv')

# Display first few rows
print(df.head())

# Features and target
X = df.drop('species', axis='columns')   # input features
y = df['species']                        # target labels

# Split dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Logistic Regression model (multiclass)
model = LogisticRegression(multi_class='multinomial', max_iter=200)

# Train model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)

cm_display = metrics.ConfusionMatrixDisplay(
    confusion_matrix=confusion_matrix,
    display_labels=df['species'].unique()
)

cm_display.plot()
plt.show()

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Upload file (Colab)
from google.colab import files
uploaded = files.upload()

# Check filename
import os
print(os.listdir())

# Load dataset (use exact filename from above)
df = pd.read_csv('HR_comma_sep.csv')

# Display basic info
print(df.head())
print(df.info())

# -------------------------------
# 1. Exploratory Data Analysis
# -------------------------------

# Check retention count
print(df['left'].value_counts())

# Group by features to see impact
print(df.groupby('left').mean(numeric_only=True))

# -------------------------------
# 2. Salary vs Retention (Bar Chart)
# -------------------------------

pd.crosstab(df['salary'], df['left']).plot(kind='bar')
plt.title("Employee Retention vs Salary")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.show()

# -------------------------------
# 3. Department vs Retention
# -------------------------------

pd.crosstab(df['Department'], df['left']).plot(kind='bar')
plt.title("Employee Retention vs Department")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.xticks(rotation=45)
plt.show()

# -------------------------------
# 4. Feature Selection
# -------------------------------

# Based on EDA, choose important variables
# (commonly: satisfaction_level, average_montly_hours, promotion_last_5years, salary)

subdf = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]

# Convert salary to dummy variables
salary_dummies = pd.get_dummies(subdf['salary'], drop_first=True)

# Combine data
df_final = pd.concat([subdf, salary_dummies], axis='columns')
df_final.drop('salary', axis='columns', inplace=True)

# Target variable
X = df_final
y = df['left']

# -------------------------------
# 5. Train-Test Split
# -------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------
# 6. Logistic Regression Model
# -------------------------------

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# -------------------------------
# 7. Prediction & Accuracy
# -------------------------------

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# -------------------------------
# 1. Upload files (for Colab)
# -------------------------------
from google.colab import files
uploaded = files.upload()

# Check uploaded files and copy exact filenames
import os
print(os.listdir())

# -------------------------------
# 2. Load datasets
# -------------------------------
# Load zoo dataset
df = pd.read_csv('zoo-data.csv')  # replace if Colab renamed it

# Load class type dataset (replace filename if renamed)
class_type_df = pd.read_csv('zoo-class-type (1).csv')

# Inspect data
print(df.head())
print(class_type_df.head())
print(df.info())

# -------------------------------
# 3. Preprocessing
# -------------------------------
# Drop unnecessary columns if any (like animal names)
if 'animal_name' in df.columns:
    df = df.drop('animal_name', axis=1)

# Convert categorical columns to numeric if needed
categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)
df = pd.get_dummies(df, drop_first=True)

# Add class_type column from class_type_df if not present
if 'class_type' not in df.columns:
    df['class_type'] = class_type_df['class_type']

# Separate features and target
X = df.drop('class_type', axis=1)
y = df['class_type']

# -------------------------------
# 4. Train-Test Split
# -------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------------
# 5. Build Logistic Regression Model
# -------------------------------
model = LogisticRegression(multi_class='multinomial', max_iter=500)
model.fit(X_train, y_train)

# -------------------------------
# 6. Predictions & Accuracy
# -------------------------------
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

# -------------------------------
# 7. Confusion Matrix (fixed)
# -------------------------------
# Ensure all classes are included in the confusion matrix
all_classes = sorted(y.unique())
cm = confusion_matrix(y_test, y_pred, labels=all_classes)

cm_display = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=all_classes)
cm_display.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix for Zoo Class Prediction")
plt.show()